//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherTravelPlanning.WeatherServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherServiceReference.IWeatherForecast")]
    public interface IWeatherForecast {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherForecast/GetWeatherForecast", ReplyAction="http://tempuri.org/IWeatherForecast/GetWeatherForecastResponse")]
        string GetWeatherForecast(string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherForecast/GetWeatherForecast", ReplyAction="http://tempuri.org/IWeatherForecast/GetWeatherForecastResponse")]
        System.Threading.Tasks.Task<string> GetWeatherForecastAsync(string zipCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherForecastChannel : WeatherTravelPlanning.WeatherServiceReference.IWeatherForecast, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherForecastClient : System.ServiceModel.ClientBase<WeatherTravelPlanning.WeatherServiceReference.IWeatherForecast>, WeatherTravelPlanning.WeatherServiceReference.IWeatherForecast {
        
        public WeatherForecastClient() {
        }
        
        public WeatherForecastClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherForecastClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherForecastClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherForecastClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWeatherForecast(string zipCode) {
            return base.Channel.GetWeatherForecast(zipCode);
        }
        
        public System.Threading.Tasks.Task<string> GetWeatherForecastAsync(string zipCode) {
            return base.Channel.GetWeatherForecastAsync(zipCode);
        }
    }
}
